In [23]:
#Importing the modules and the dataset
import pandas as pd 
import numpy as np


df=pd.read_csv('dataset.csv')


In [2]:
df.head()

Id  MSSubClass MSZoning  LotFrontage  LotArea Street Alley LotShape  \
0   1          60       RL         65.0     8450   Pave   NaN      Reg   
1   2          20       RL         80.0     9600   Pave   NaN      Reg   
2   3          60       RL         68.0    11250   Pave   NaN      IR1   
3   4          70       RL         60.0     9550   Pave   NaN      IR1   
4   5          60       RL         84.0    14260   Pave   NaN      IR1   

  LandContour Utilities  ... PoolArea PoolQC Fence MiscFeature MiscVal MoSold  \
0         Lvl    AllPub  ...        0    NaN   NaN         NaN       0      2   
1         Lvl    AllPub  ...        0    NaN   NaN         NaN       0      5   
2         Lvl    AllPub  ...        0    NaN   NaN         NaN       0      9   
3         Lvl    AllPub  ...        0    NaN   NaN         NaN       0      2   
4         Lvl    AllPub  ...        0    NaN   NaN         NaN       0     12   

  YrSold  SaleType  SaleCondition  SalePrice  
0   2008        WD         Normal     208500  
1   2007        WD         Normal     181500  
2   2008        WD         Normal     223500  
3   2006        WD        Abnorml     140000  
4   2008        WD         Normal     250000  

[5 rows x 81 columns]

In [27]:
#dealing with missing data
total = df.isnull().sum().sort_values(ascending=False)
percent = (df.isnull().sum()/df.isnull().count()).sort_values(ascending=False)
missing_data = pd.concat([total, percent], axis=1, keys=['Total', 'Percent'])
missing_data.head(20)


Total   Percent
Electrical        1  0.000685
SalePrice         0  0.000000
Heating           0  0.000000
BsmtUnfSF         0  0.000000
BsmtFinSF2        0  0.000000
BsmtFinSF1        0  0.000000
Foundation        0  0.000000
ExterCond         0  0.000000
ExterQual         0  0.000000
Exterior2nd       0  0.000000
Exterior1st       0  0.000000
RoofMatl          0  0.000000
RoofStyle         0  0.000000
YearRemodAdd      0  0.000000
YearBuilt         0  0.000000
OverallCond       0  0.000000
OverallQual       0  0.000000
HouseStyle        0  0.000000
BldgType          0  0.000000
Condition2        0  0.000000

In [28]:
#To ensure no missing data is there
df = df.drop((missing_data[missing_data['Total'] > 1]).index,1)
df = df.drop(df.loc[df['Electrical'].isnull()].index)
df.isnull().sum().max() #just checking that there's no missing data missing...



0

In [29]:
#to ensure the percentage of missing data per column
total = df.isnull().sum().sort_values(ascending=False)
percent = (df.isnull().sum()/df_train.isnull().count()).sort_values(ascending=False)
missing_data = pd.concat([total, percent], axis=1, keys=['Total', 'Percent'])
missing_data.head(20)

Total  Percent
SalePrice         0      0.0
OverallQual       0      0.0
BsmtUnfSF         0      0.0
BsmtFinSF2        0      0.0
BsmtFinSF1        0      0.0
Foundation        0      0.0
ExterCond         0      0.0
ExterQual         0      0.0
Exterior2nd       0      0.0
Exterior1st       0      0.0
RoofMatl          0      0.0
RoofStyle         0      0.0
YearRemodAdd      0      0.0
YearBuilt         0      0.0
OverallCond       0      0.0
HouseStyle        0      0.0
Heating           0      0.0
BldgType          0      0.0
Condition2        0      0.0
Condition1        0      0.0

In [30]:
#To scale the SalePrice Column
from sklearn.preprocessing import StandardScaler
saleprice_scaled = StandardScaler().fit_transform(df_train['SalePrice'][:,np.newaxis]);
low_range = saleprice_scaled[saleprice_scaled[:,0].argsort()][:10]
high_range= saleprice_scaled[saleprice_scaled[:,0].argsort()][-10:]
print('outer range (low) of the distribution:')
print(low_range)
print('\nouter range (high) of the distribution:')
print(high_range)

outer range (low) of the distribution:
[[-1.83820775]
 [-1.83303414]
 [-1.80044422]
 [-1.78282123]
 [-1.77400974]
 [-1.62295562]
 [-1.6166617 ]
 [-1.58519209]
 [-1.58519209]
 [-1.57269236]]

outer range (high) of the distribution:
[[3.82758058]
 [4.0395221 ]
 [4.49473628]
 [4.70872962]
 [4.728631  ]
 [5.06034585]
 [5.42191907]
 [5.58987866]
 [7.10041987]
 [7.22629831]]


In [31]:
#To covert the dtypes of certain columns
df['MSSubClass'] = df['MSSubClass'].apply(str)


#Changing OverallCond into a categorical variable
df['OverallCond'] = df['OverallCond'].astype(str)


#Year and month sold are transformed into categorical features.
df['YrSold'] = df['YrSold'].astype(str)
df['MoSold'] = df['MoSold'].astype(str)

In [8]:
df.shape

(1459, 63)

In [9]:
df.columns

Index(['Id', 'MSSubClass', 'MSZoning', 'LotArea', 'Street', 'LotShape',
       'LandContour', 'Utilities', 'LotConfig', 'LandSlope', 'Neighborhood',
       'Condition1', 'Condition2', 'BldgType', 'HouseStyle', 'OverallQual',
       'OverallCond', 'YearBuilt', 'YearRemodAdd', 'RoofStyle', 'RoofMatl',
       'Exterior1st', 'Exterior2nd', 'ExterQual', 'ExterCond', 'Foundation',
       'BsmtFinSF1', 'BsmtFinSF2', 'BsmtUnfSF', 'TotalBsmtSF', 'Heating',
       'HeatingQC', 'CentralAir', 'Electrical', '1stFlrSF', '2ndFlrSF',
       'LowQualFinSF', 'GrLivArea', 'BsmtFullBath', 'BsmtHalfBath', 'FullBath',
       'HalfBath', 'BedroomAbvGr', 'KitchenAbvGr', 'KitchenQual',
       'TotRmsAbvGrd', 'Functional', 'Fireplaces', 'GarageCars', 'GarageArea',
       'PavedDrive', 'WoodDeckSF', 'OpenPorchSF', 'EnclosedPorch', '3SsnPorch',
       'ScreenPorch', 'PoolArea', 'MiscVal', 'MoSold', 'YrSold', 'SaleType',
       'SaleCondition', 'SalePrice'],
      dtype='object')

In [32]:
#To encode the categorical columns by using LabelEncoder
from sklearn.preprocessing import LabelEncoder
cols = ('ExterQual', 'ExterCond','HeatingQC',  'KitchenQual', 'Functional', 'LandSlope',
        'LotShape', 'PavedDrive', 'Street',  'CentralAir', 'MSSubClass', 'OverallCond', 
        'YrSold', 'MoSold')
# process columns, apply LabelEncoder to categorical features
for c in cols:
    lbl = LabelEncoder() 
    lbl.fit(list(df[c].values)) 
    df[c] = lbl.transform(list(df[c].values))

# shape        
print('Shape all_data: {}'.format(df.shape))

Shape all_data: (1459, 63)


In [9]:
#To separate X and Y
X=df.copy()

In [10]:
X.drop(columns='SalePrice',axis=1,inplace=True)

In [11]:
Y=df['SalePrice']

In [19]:
#To partition the dataset to train and test
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, Y, test_size = 0.15, random_state = 0)


In [20]:
#Predicting the Price by applying RandomForest Regressor
#Random Forest Regression
from sklearn.ensemble import RandomForestRegressor
regressor = RandomForestRegressor(n_estimators = 150, random_state = 0,max_depth=50)
regressor.fit(X_train, y_train)

#Linear Regression
# from sklearn.linear_model import LinearRegression
# regressor = LinearRegression()
# regressor.fit(X_train, y_train)

#SVM
# from sklearn.svm import SVR
# regressor = SVR(kernel = 'rbf')
# regressor.fit(X_train, y_train)

# from sklearn.tree import DecisionTreeRegressor
# regressor = DecisionTreeRegressor(random_state = 0)
# regressor.fit(X_train, y_train)


# Predicting a new result
y_pred = regressor.predict(X_test)

y_pred

array([161931.70666667, 103808.        ,  92090.52666667, 142242.58      ,
       141394.        , 129638.00666667, 164980.16      , 188253.47333333,
        93456.36      , 117548.        , 106963.90666667, 321498.72      ,
        95940.        , 211748.09333333, 333732.4       , 156202.70666667,
       148033.46      , 374949.81333333, 310410.07333333, 156942.6       ,
       335581.46666667,  94447.07333333, 145852.52      , 197987.14      ,
       181393.        , 191804.76      , 154018.39333333, 299745.36666667,
        74016.33333333, 337020.76666667, 121752.5       , 145863.66666667,
       151608.        , 165036.54666667, 231534.88      , 286969.60666667,
       118711.        , 184188.66666667, 118430.22      , 126410.10666667,
       110288.25333333, 151092.94      , 235987.25333333,  83262.66666667,
       138025.        , 210170.33333333, 188188.16666667, 189207.64      ,
       123277.33333333, 266418.50666667, 284081.02666667, 146360.66666667,
        71616.37333333,  

In [26]:
X.head()

Id  MSSubClass  LotArea  Street  LotShape  LandSlope  Neighborhood  \
0   1           9     8450       1         3          0             5   
1   2           4     9600       1         3          0            24   
2   3           9    11250       1         0          0             5   
3   4          10     9550       1         0          0             6   
4   5           9    14260       1         0          0            15   

   Condition1  Condition2  BldgType  ...  OpenPorchSF  EnclosedPorch  \
0           2           2         0  ...           61              0   
1           1           2         0  ...            0              0   
2           2           2         0  ...           42              0   
3           2           2         0  ...           35            272   
4           2           2         0  ...           84              0   

   3SsnPorch  ScreenPorch  PoolArea  MiscVal  MoSold  YrSold  SaleType  \
0          0            0         0        0       4       2         8   
1          0            0         0        0       7       1         8   
2          0            0         0        0      11       2         8   
3          0            0         0        0       4       0         8   
4          0            0         0        0       3       2         8   

   SaleCondition  
0              4  
1              4  
2              4  
3              0  
4              4  

[5 rows x 58 columns]

In [17]:
X.drop(columns=['MSZoning','LandContour','Utilities','LotConfig'],inplace=True)

In [21]:
X.head()

Id  MSSubClass  LotArea  Street  LotShape  LandSlope Neighborhood  \
0   1           9     8450       1         3          0      CollgCr   
1   2           4     9600       1         3          0      Veenker   
2   3           9    11250       1         0          0      CollgCr   
3   4          10     9550       1         0          0      Crawfor   
4   5           9    14260       1         0          0      NoRidge   

  Condition1 Condition2 BldgType  ... OpenPorchSF  EnclosedPorch  3SsnPorch  \
0       Norm       Norm     1Fam  ...          61              0          0   
1      Feedr       Norm     1Fam  ...           0              0          0   
2       Norm       Norm     1Fam  ...          42              0          0   
3       Norm       Norm     1Fam  ...          35            272          0   
4       Norm       Norm     1Fam  ...          84              0          0   

   ScreenPorch  PoolArea MiscVal MoSold YrSold SaleType  SaleCondition  
0            0         0       0      4      2       WD         Normal  
1            0         0       0      7      1       WD         Normal  
2            0         0       0     11      2       WD         Normal  
3            0         0       0      4      0       WD        Abnorml  
4            0         0       0      3      2       WD         Normal  

[5 rows x 58 columns]

In [18]:
from sklearn.preprocessing import LabelEncoder
cols = ('Neighborhood', 'Condition1','Condition2',  'BldgType', 'SaleType', 'SaleCondition','HouseStyle','RoofStyle','RoofMatl',
        'Exterior1st','Exterior2nd','Foundation','Heating','Electrical'
       )
# process columns, apply LabelEncoder to categorical features
for c in cols:
    lbl = LabelEncoder() 
    lbl.fit(list(X[c].values)) 
    X[c] = lbl.transform(list(X[c].values))

# shape        
print('Shape all_data: {}'.format(X.shape))

Shape all_data: (1459, 58)


In [21]:
#Accuracy of the model by manual calculation
errors = abs(y_pred - y_test)
# Display the performance metrics
print('Mean Absolute Error:', round(np.mean(errors), 2), 'degrees.')
mape = np.mean(100 * (errors / y_test))
accuracy = 100 - mape
print('Accuracy:', round(accuracy, 2), '%.')

Mean Absolute Error: 17492.98 degrees.
Accuracy: 89.15 %.
